GET http://localhost:3000/alumnos
###
GET http://localhost:3000/alumnos/5
###
POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "id": "6",
    "nombre": "Lucresia",
    "carrera": "Maestra de Cuidados Especiales"
}
###
POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "id": 8,
    "nombre": "Raúl Alejandro",
    "carrera": "AAAAAAHHHHHHHHHH"
}
###
PUT http://localhost:3000/alumnos/3
Content-Type: application/json

{
    "id": 3,
    "nombre": "Negro",
    "carrera": "Negradas"
}
###
GET http://localhost:3000/alumnos/2
###
DELETE http://localhost:3000/alumnos/2