GET http://localhost:3001/alumnos
###
GET http://localhost:3001/alumnos/2001
###
POST http://localhost:3001/alumnos
Content-Type: application/json

{
    "legajo": 820000,
    "nombre": "Lucia",
    "carrera": "Maestra de Cuidados No Especiales", 
    "correo": "Lucia@gmail.com"
}
###
PUT http://localhost:3001/alumnos/8563
Content-Type: application/json

{
    "nombre": "Negra",
    "carrera": "Negradas", 
    "correo": "negrosanonimos@gmail.com"
}
###
DELETE http://localhost:3001/alumnos/8563

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
###
GET http://localhost:3001/docentes
###
GET http://localhost:3001/docentes/3582
###
POST http://localhost:3001/docentes
Content-Type: application/json

{
    "legajo": 6666,
    "nombre": "Lucia",
    "especialidad": "Maestra de Cuidados No Especiales", 
    "correo": "Lucia@gmail.com"
}
###
PUT http://localhost:3001/docentes/6666
Content-Type: application/json

{
    "nombre": "NNNNNN",
    "especialidad": "nnnnnnnnnnnnnnnnnnnnnnnnnn", 
    "correo": "nnnnnn@nnnnnnnnnnnnn"
}
###
DELETE http://localhost:3001/docentes/6666